version: '2'
services:
  backend:
    container_name: "spend-crawler"
    image: spend-image
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=[username]
      - MONGODB_PASSWORD=[password]
    links:
      - mongo
  mongo:
    image: "mongo:latest"
    environment:
      - MONGODB_ROOT_PASSWORD=[root_pass]
    container_name: "spend-mongodb"
