version: '3.8'
services:
  spend:
    build: .
    container_name: spend
    image: spend-image
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
    links:
      - mongo
    ports:
      - 5000:5000
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: spend-mongodb
    restart: unless-stopped

  mongoimport:
    image: mongo:latest
    container_name: spend-import
    volumes:
      - ./mongo-seed/keywords.json:/mongo-seed/keywords.json
      - ./mongo-seed/users.json:/mongo-seed/users.json
    command: bash -c "mongoimport --host mongo -d SpEnD-DB -c keywords --type json --file /mongo-seed/keywords.json --jsonArray
      && mongoimport --host mongo -d SpEnD-DB -c users --type json --file /mongo-seed/users.json --jsonArray"
    restart: on-failure