version: '2'
services:
  backend:
    image: spend-image
    container_name: "spend-crawler"
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_USERNAME=[username]
      - MONGODB_PASSWORD=[password]
    links:
      - mongo
    restart: on-failure

  mongo:
    image: "mongo:latest"
    container_name: "spend-mongodb"
    environment:
      - MONGODB_ROOT_PASSWORD=[root_pass]
    depends_on:
      - mongoimport
    restart: unless-stopped

  mongoimport:
    image: mongo:latest
    container_name: spend-import
    volumes:
      - ./data/keywords.json:/data/keywords.json
    command: mongoimport --host mongo -d SpEnD-DB -c Keywords --type json --file /data/keywords.json --jsonArray
    restart: on-failure